# Copyright (c) 2026, ERPNext Extensions contributors
# License: MIT

from __future__ import annotations

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

from erpnext_extensions.consignment_stock.material_loan.constants import (
	F_EXPECTED_RETURN_DATE,
	F_EXTERNAL_REF,
	F_IS_LOAN_ISSUE,
	F_IS_LOAN_RETURN,
	F_ISSUE_DETAIL,
	F_ISSUE_QTY,
	F_ISSUE_RATE,
	F_ISSUE_REF_HEADER,
	F_ISSUE_SE,
	F_ISSUE_VALUE,
	F_JE_ROLE,
	F_PARTY,
	F_PARTY_TYPE,
	F_PHYSICAL_STATUS,
	F_PREV_RETURNED_QTY,
	F_RECOGNITION_JE,
	F_RECOGNITION_STATUS,
	F_REMAINING_QTY,
	F_RETURN_VALUE,
	F_SETTLEMENT_AMOUNT,
	F_SETTLEMENT_JE,
	F_SETTLEMENT_STATUS,
	JE_ROLE_RECOGNITION,
	JE_ROLE_SETTLEMENT,
	MODULE,
	PHYSICAL_STATUS_OPTIONS,
	RECOGNITION_STATUS_OPTIONS,
	SETTLEMENT_STATUS_OPTIONS,
)


def get_custom_fields() -> dict:
	loan_flag_depends = f"eval:doc.{F_IS_LOAN_ISSUE}||doc.{F_IS_LOAN_RETURN}"
	return {
		"Stock Entry Type": [
			{
				"fieldname": F_IS_LOAN_ISSUE,
				"label": "Material Loan Issue",
				"fieldtype": "Check",
				"insert_after": "custom_is_consignment_return",
				"depends_on": "eval:doc.purpose=='Material Issue'",
				"description": "Material Issue lending company-owned materials to a party",
				"module": MODULE,
			},
			{
				"fieldname": F_IS_LOAN_RETURN,
				"label": "Material Loan Return",
				"fieldtype": "Check",
				"insert_after": F_IS_LOAN_ISSUE,
				"depends_on": "eval:doc.purpose=='Material Receipt'",
				"description": "Material Receipt returning loaned materials",
				"module": MODULE,
			},
		],
		"Stock Entry": [
			{
				"fieldname": "custom_material_loan_section",
				"label": "Material Loan",
				"fieldtype": "Section Break",
				"insert_after": "custom_consignment_status",
				"collapsible": 1,
				"depends_on": loan_flag_depends,
				"module": MODULE,
			},
			{
				"fieldname": F_IS_LOAN_ISSUE,
				"label": "Is Material Loan Issue",
				"fieldtype": "Check",
				"read_only": 1,
				"fetch_from": f"stock_entry_type.{F_IS_LOAN_ISSUE}",
				"insert_after": "custom_material_loan_section",
				"module": MODULE,
			},
			{
				"fieldname": F_IS_LOAN_RETURN,
				"label": "Is Material Loan Return",
				"fieldtype": "Check",
				"read_only": 1,
				"fetch_from": f"stock_entry_type.{F_IS_LOAN_RETURN}",
				"insert_after": F_IS_LOAN_ISSUE,
				"module": MODULE,
			},
			{
				"fieldname": F_PARTY_TYPE,
				"label": "Material Loan Party Type",
				"fieldtype": "Link",
				"options": "DocType",
				"insert_after": F_IS_LOAN_RETURN,
				"depends_on": loan_flag_depends,
				"mandatory_depends_on": loan_flag_depends,
				"module": MODULE,
			},
			{
				"fieldname": F_PARTY,
				"label": "Material Loan Party",
				"fieldtype": "Dynamic Link",
				"options": F_PARTY_TYPE,
				"insert_after": F_PARTY_TYPE,
				"depends_on": loan_flag_depends,
				"mandatory_depends_on": loan_flag_depends,
				"module": MODULE,
			},
			{
				"fieldname": "custom_material_loan_col_break",
				"fieldtype": "Column Break",
				"insert_after": F_PARTY,
				"module": MODULE,
			},
			{
				"fieldname": F_PHYSICAL_STATUS,
				"label": "Material Loan Physical Status",
				"fieldtype": "Select",
				"options": PHYSICAL_STATUS_OPTIONS,
				"insert_after": "custom_material_loan_col_break",
				"read_only": 1,
				"no_copy": 1,
				"depends_on": loan_flag_depends,
				"module": MODULE,
			},
			{
				"fieldname": F_RECOGNITION_STATUS,
				"label": "Material Loan Recognition Status",
				"fieldtype": "Select",
				"options": RECOGNITION_STATUS_OPTIONS,
				"insert_after": F_PHYSICAL_STATUS,
				"read_only": 1,
				"no_copy": 1,
				"depends_on": f"eval:doc.{F_IS_LOAN_ISSUE}",
				"module": MODULE,
			},
			{
				"fieldname": F_SETTLEMENT_STATUS,
				"label": "Material Loan Settlement Status",
				"fieldtype": "Select",
				"options": SETTLEMENT_STATUS_OPTIONS,
				"insert_after": F_RECOGNITION_STATUS,
				"read_only": 1,
				"no_copy": 1,
				"depends_on": f"eval:doc.{F_IS_LOAN_ISSUE}",
				"module": MODULE,
			},
			{
				"fieldname": F_EXPECTED_RETURN_DATE,
				"label": "Expected Return Date",
				"fieldtype": "Date",
				"insert_after": F_SETTLEMENT_STATUS,
				"depends_on": f"eval:doc.{F_IS_LOAN_ISSUE}",
				"module": MODULE,
			},
			{
				"fieldname": F_EXTERNAL_REF,
				"label": "External Reference",
				"fieldtype": "Data",
				"insert_after": F_EXPECTED_RETURN_DATE,
				"depends_on": f"eval:doc.{F_IS_LOAN_ISSUE}",
				"module": MODULE,
			},
			{
				"fieldname": F_ISSUE_REF_HEADER,
				"label": "Default Material Loan Issue",
				"fieldtype": "Link",
				"options": "Stock Entry",
				"insert_after": F_EXTERNAL_REF,
				"depends_on": f"eval:doc.{F_IS_LOAN_RETURN}",
				"module": MODULE,
			},
			{
				"fieldname": F_RECOGNITION_JE,
				"label": "Material Loan Recognition JE",
				"fieldtype": "Link",
				"options": "Journal Entry",
				"insert_after": F_ISSUE_REF_HEADER,
				"read_only": 1,
				"no_copy": 1,
				"depends_on": f"eval:doc.{F_IS_LOAN_ISSUE}",
				"module": MODULE,
			},
			{
				"fieldname": F_SETTLEMENT_JE,
				"label": "Material Loan Settlement JE",
				"fieldtype": "Link",
				"options": "Journal Entry",
				"insert_after": F_RECOGNITION_JE,
				"read_only": 1,
				"no_copy": 1,
				"depends_on": f"eval:doc.{F_IS_LOAN_RETURN}",
				"module": MODULE,
			},
		],
		"Stock Entry Detail": [
			{
				"fieldname": "custom_material_loan_detail_section",
				"label": "Material Loan Reference",
				"fieldtype": "Section Break",
				"insert_after": "custom_consignment_settlement_amount",
				"collapsible": 1,
				"module": MODULE,
			},
			{
				"fieldname": F_ISSUE_SE,
				"label": "Material Loan Issue",
				"fieldtype": "Link",
				"options": "Stock Entry",
				"insert_after": "custom_material_loan_detail_section",
				"module": MODULE,
			},
			{
				"fieldname": F_ISSUE_DETAIL,
				"label": "Material Loan Issue Row",
				"fieldtype": "Data",
				"insert_after": F_ISSUE_SE,
				"module": MODULE,
			},
			{
				"fieldname": F_ISSUE_RATE,
				"label": "Original Issue Rate",
				"fieldtype": "Currency",
				"options": "Company:company:default_currency",
				"read_only": 1,
				"insert_after": F_ISSUE_DETAIL,
				"module": MODULE,
			},
			{
				"fieldname": F_ISSUE_VALUE,
				"label": "Original Issue Value",
				"fieldtype": "Currency",
				"options": "Company:company:default_currency",
				"read_only": 1,
				"insert_after": F_ISSUE_RATE,
				"module": MODULE,
			},
			{
				"fieldname": F_ISSUE_QTY,
				"label": "Original Issue Qty",
				"fieldtype": "Float",
				"read_only": 1,
				"insert_after": F_ISSUE_VALUE,
				"module": MODULE,
			},
			{
				"fieldname": F_PREV_RETURNED_QTY,
				"label": "Previously Returned Qty",
				"fieldtype": "Float",
				"read_only": 1,
				"insert_after": F_ISSUE_QTY,
				"module": MODULE,
			},
			{
				"fieldname": F_REMAINING_QTY,
				"label": "Remaining Returnable Qty",
				"fieldtype": "Float",
				"read_only": 1,
				"insert_after": F_PREV_RETURNED_QTY,
				"module": MODULE,
			},
			{
				"fieldname": F_RETURN_VALUE,
				"label": "Material Loan Return Value",
				"fieldtype": "Currency",
				"options": "Company:company:default_currency",
				"read_only": 1,
				"insert_after": F_REMAINING_QTY,
				"module": MODULE,
			},
			{
				"fieldname": F_SETTLEMENT_AMOUNT,
				"label": "Material Loan Settlement Amount",
				"fieldtype": "Currency",
				"options": "Company:company:default_currency",
				"read_only": 1,
				"insert_after": F_RETURN_VALUE,
				"module": MODULE,
			},
		],
		"Journal Entry": [
			{
				"fieldname": F_JE_ROLE,
				"label": "Material Loan JE Role",
				"fieldtype": "Select",
				"options": f"\n{JE_ROLE_RECOGNITION}\n{JE_ROLE_SETTLEMENT}",
				"insert_after": "custom_consignment_je_role",
				"read_only": 1,
				"no_copy": 1,
				"module": MODULE,
			},
		],
	}


def ensure_custom_fields() -> None:
	from erpnext_extensions.consignment_stock.party_type_meta import (
		repair_stock_entry_party_type_link_options,
	)

	# Repair invalid Dynamic Link controllers before create_custom_fields validates meta.
	repair_stock_entry_party_type_link_options()
	create_custom_fields(get_custom_fields(), update=True)
