SETTLEMENT_PI = "Purchase Invoice"
SETTLEMENT_SA = "Supplier Advance"

EPSILON = 1e-6

FUNDING_SOURCE_PM_REQUEST = "PM Request"
FUNDING_SOURCE_OPENING_ADVANCE = "PM Opening Advance"

OPENING_SOURCE_OPENING_BALANCE = "Opening Balance"
OPENING_SOURCE_LEGACY_ADVANCE = "Legacy Advance"
OPENING_SOURCE_BRANCH_TRANSFER = "Branch Transfer"
OPENING_SOURCE_MANUAL_ADJUSTMENT = "Manual Adjustment"

OPENING_SOURCE_TYPES = (
	OPENING_SOURCE_OPENING_BALANCE,
	OPENING_SOURCE_LEGACY_ADVANCE,
	OPENING_SOURCE_BRANCH_TRANSFER,
	OPENING_SOURCE_MANUAL_ADJUSTMENT,
)

